migrate the code of prow tide
opensourceways/robot-gitee-tide pull request #3
Opened 2022-01-04 09:47 UTC by xwz123

2022-01-07 09:26 UTC, zengchen1024 requested changes

2022-01-07 09:26 UTC, zengchen1024 commented on robot.go
> +	if e.GetState() != sdk.ActionOpen {
e.GetPullRequest().GetState()

2022-01-07 09:26 UTC, zengchen1024 commented on robot.go
> +	cli iClient
add a member of botName to avoid get it on pr event

2022-01-07 09:26 UTC, zengchen1024 commented on robot.go
> +	b, err := bot.cli.GetBot()
use bot.botName

2022-01-07 09:26 UTC, zengchen1024 commented on robot.go
> +		return nil
https://github.com/opensourceways/test-infra/blob/sync-5-22/prow/gitee-plugins/tide/tide.go#L138

2022-01-07 09:26 UTC, zengchen1024 commented on robot.go
> +	tideNotification   = "@%s, This pr is not mergeable."
not used

2022-01-07 09:32 UTC, zengchen1024 commented
think about the operation logs.

2022-01-22 01:56 UTC, zengchen1024 commented
did you reset the number of reviewer and tester to zero?

2022-01-25 08:20 UTC, chenzeng765 requested changes

2022-01-25 08:20 UTC, chenzeng765 commented on label.go
> +		if labels.Has(l.Label) {
if !labels.Has(l.Label)

2022-01-25 08:20 UTC, chenzeng765 commented on robot.go
> +	if e.GetPullRequest().GetState() != sdk.ActionOpen {
sdk.StatusOpen

2022-01-26 01:11 UTC, merged